[tox]
envlist = py35,py36,py37,py38,py39,py310,py311,py312,py313
minversion = 3.3.0
isolated_build = True

[testenv]
deps =
    check-manifest >= 0.42
    pytest
    pytest-cov
commands =
    check-manifest --ignore 'tox.ini,tests/**,.editorconfig,vscode.env,.vscode/**'
    python setup.py check -m -s
    pytest --cov-report=xml --cov=tests tests {posargs}
